version: '3.8'

services:
  my-redis:
    container_name: my-redis
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    external: true